### ISSUE TITLE
请教一下，你的机器 NVME SSD 速度正常吗？ 我测试大概只有 PCIE3.0 1x 的速度

### ISSUE THREAD

**Issue by tanpengsccd** [cgistar/hackis#5]
![image](https://user-images.githubusercontent.com/13959880/105294697-66379a80-5bf4-11eb-9f79-18e29ab776c0.png)

是东芝 铠侠RC10

**Comment by cgistar** [comment]
一样的东芝 [铠侠RC10]
![image](https://user-images.githubusercontent.com/10128746/105924949-3d8f2500-607a-11eb-9e0c-b0791a606335.png)

**Comment by tanpengsccd** [comment]
我的U是转接板U 所以PCIe 那里有问题。速度只有一半。谢谢答复。

sean <notifications@github.com>于2021年1月27日 周三上午8:33写道：
